services:
  - type: web
    name: minio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: admin123456
